### ISSUE TITLE
Any way to make the script work with directories outside of its own?

### ISSUE THREAD

**Issue by yusufcardinal** [lorenzos/Minixed#15]
I've been modifying the script so it may be able to list files in a directory other than its own. The website resides at /www/html/ , and the script is placed in folder /www/html/foo/bar/ . It is meant to list files in /medias/foo/bar/ .

I have managed to list the files of the /medias/foo/bar/ directory on the webpage, but I am struggling to get the subdirectory navigation to work.

**Comment by tim-elmer** [comment]
It'd be helpful to know what you've changed and what the permissions to `/medias/foo/bar` look like.

**Comment by yusufcardinal** [comment]
Sorry, I pressed post way too early.

I've forked the version of lorenzos and replaced it with my version.  The relevant changes are in the latest commit, line 45 onward. The permissions of /medias/foo/bar are okay because I am able to get the directory listing and open files that are at the root of /medias/foo/bar , I only find myself unable to open subdirectories.

**Comment by lorenzos** [comment]
@yusufcardinal I don't know if it's the only cause, but take a look at [line 60](https://github.com/yusufcardinal/Minixed/commit/4e6479a773d2d1e54b96f73e0952bdded2cceac9#diff-7413d6453f901e939bbd840c8f0d1c7b20c2ca0e7f71741e4e07c6cf036f16c0R60) in your modified script. There's a check (the last condition) that makes sure the `b` URL parameter is in fact a directory name, using `is_dir()`. That check fails because `b` is relative to the script location, and so the `$_browse` is never set. You should prefix both the check and `$_browse` with your starting path.

**Comment by lorenzos** [comment]
Also, why not using a symlink instead of modifying the script?

```sh
cd /www/html/foo/bar
wget https://raw.githubusercontent.com/lorenzos/Minixed/master/index.php
ln -s /medias/foo/bar/ ./baz
```

And configure the script like:

```php
$browseDirectories = true;
$browseDefault = 'baz'
```
