### ISSUE TITLE
Start directory

### ISSUE THREAD

**Issue by cramdesign** [lorenzos/Minixed#9]
Could we create a setting variable that would allow the start directory to be other than the same directory as the php file?

**Comment by lorenzos** [comment]
Thanks for this suggestion too :smiley: I added a new `$browseDefault` configuration variable, but I didn't documented it since it's quite a "peculiar" use case, and anyway the comment is sufficient.

You can set it to the name of a subfolder or sub-subfolder (i.e. `mydir` or `mydir/mysubdir`), and the script will browse "by default" into it when called without the `b` parameter; however if the`b` parameter is present but empty (i.e. `?b=`) the script will browse to the root directory (this is necessary to have a way to go up to the root). Remember that `$browseDirectories` has to be enabled to make this work.
